version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
ellojess-patch-1
      jobs:
      build:
        executor: ci-executor
        steps:
          - checkout